enabled: true
deploymentName: "helloworld"
namespace: "app-microservices"
containerName: "helloworld"
distributed_tracing_enabled: "true"
log_level: "info"
log: "stdout"
app_name: "helloworld"
version: 0.0.1
env: "dev"
release: "helloworld"

# Service Values
serviceName: "helloworld"

# ServiceAccount
ksaServiceAccount: helloworld-sa
gcpServiceAccount: product-service-sa@noble-linker-471623-s6.iam.gserviceaccount.com
cicdKsaServiceAccount: helloworld-ci-cd-sa
cicdGcpServiceAccount: ci-cd-sa@noble-linker-471623-s6.iam.gserviceaccount.com

datasource:
  username:

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

# App image details (replaced by helm)
image:
  repository: "us-central1-docker.pkg.dev/noble-linker-471623-s6/onlineliquorservicesartifactory/helloworld"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred

#Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

# Replica count for the deployment
replicaCount: 1

#The Key of node labels
topologyKey: "topology.kubernetes.io/zone"

service:
  type: LoadBalancer
  portName: http
  port: 80
  TargetPort: 8083
  annotations:
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
    networking.gkr.io/load-balancer-type: "Internal"

# Resource Limits
resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: "500m"
    memory: 256Mi
nodeSelector: { }
tolerations: [ ]
affinity: { }
